name: NBA Dashboard ECR Deployment

on:
  push:
    branches:
    - main

env:
  IAM_ROLE: ${{ secrets.IAM_ROLE }}
  AWS_REGION : "us-east-1"
  ECR_REPO : ${{ secrets.ECR_REPO }}

# permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      if: github.ref == 'refs/heads/main'

    - name: Create and populate .Renviron file
      env:
        AWS_HOST: ${{ secrets.AWS_HOST }}
        AWS_PORT: ${{ secrets.AWS_PORT }}
        AWS_PW: ${{ secrets.AWS_PW }}
        AWS_USER: ${{ secrets.AWS_USER }}
        AWS_DB: ${{ secrets.AWS_DB }}
      run: |
        touch .Renviron
        echo aws_host="$AWS_HOST" >> .Renviron
        echo aws_port="$AWS_PORT" >> .Renviron
        echo aws_pw="$AWS_PW" >> .Renviron
        echo aws_user="$AWS_USER" >> .Renviron
        echo aws_db="$AWS_DB" >> .Renviron
      shell: bash


    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.IAM_ROLE }}            # use full arn
        role-session-name: nba-dashboard-cicd
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      if: github.ref == 'refs/heads/main'

    - name: Build, tag, and push image to Amazon ECR
      if: github.ref == 'refs/heads/main'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPO }}
        IMAGE_TAG: shiny_app
      run: |
        docker compose -f docker/docker-compose-deploy.yml build
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG